import type { Metadata } from "next";
import SiteHeader from "@/components/marketing/SiteHeader";
import SiteFooter from "@/components/marketing/SiteFooter";
import { CONTACT, addressOneLine } from "@/lib/site";

export const metadata: Metadata = {
  title: "Privacy Policy — Strollo",
  description: "How Strollo collects, uses, and protects your data.",
};

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mt-10">
      <h2 className="font-display text-xl font-bold text-navy-700">{title}</h2>
      <div className="mt-3 space-y-3 text-sm leading-relaxed text-ink/70">{children}</div>
    </div>
  );
}

export default function PrivacyPage() {
  return (
    <main className="bg-paper">
      <SiteHeader />

      <section className="mx-auto max-w-3xl px-6 py-16 sm:py-20">
        <span className="text-sm font-bold uppercase tracking-wide text-sky-600">Legal</span>
        <h1 className="mt-3 font-display text-4xl font-extrabold text-navy-700 sm:text-5xl">
          Privacy Policy
        </h1>
        <p className="mt-4 text-sm text-ink/50">Last updated: 13 August 2026</p>
        <p className="mt-6 text-base leading-relaxed text-ink/70">
          This policy explains what information Strollo ("we", "us") collects when you use our
          website and app to book and manage dog walks, and how that information is used, stored,
          and shared.
        </p>

        <Section title="1. Information we collect">
          <p>We collect information you give us directly, and information generated by using the service:</p>
          <ul className="ml-5 list-disc space-y-1.5">
            <li>
              <strong>Account details:</strong> your name and mobile number (used to log in via
              OTP), and email address if you add one.
            </li>
            <li>
              <strong>Dog details:</strong> your dog's name, breed, age, weight, gender,
              vaccination status, and any medical or behavioural notes you choose to add.
            </li>
            <li>
              <strong>Addresses:</strong> the addresses you save for walks, including the exact
              map location (latitude/longitude) you pick, so a walker can find the right spot.
            </li>
            <li>
              <strong>Walk data:</strong> the GPS route, distance, and duration of each walk, plus
              any photos and notes your walker adds during the visit.
            </li>
            <li>
              <strong>Payment data:</strong> booking amounts and payment status. Card and UPI
              details are handled entirely by Razorpay, our payment processor — we never see or
              store your full card or bank details.
            </li>
            <li>
              <strong>Messages you send us:</strong> anything you submit through the Contact Us
              form.
            </li>
          </ul>
        </Section>

        <Section title="2. How we use your information">
          <ul className="ml-5 list-disc space-y-1.5">
            <li>To create and manage your account, and verify it's really you via OTP.</li>
            <li>To schedule, assign, and track walks, and to show you and your walker the right pickup location.</li>
            <li>To process payments and generate GST tax invoices for completed bookings.</li>
            <li>To send booking, walk, and payment updates by in-app notification and, if you have an email on file, by email.</li>
            <li>To check whether your address falls within an area we currently service.</li>
            <li>To respond to messages you send us.</li>
          </ul>
        </Section>

        <Section title="3. Who we share it with">
          <p>We don't sell your data. We share the minimum necessary with:</p>
          <ul className="ml-5 list-disc space-y-1.5">
            <li>
              <strong>Your assigned walker</strong> — your dog's details, address, and any notes
              needed to carry out the walk safely.
            </li>
            <li>
              <strong>Razorpay</strong> — to process payments and refunds.
            </li>
            <li>
              <strong>Our cloud storage and email providers</strong> — to store dog/walk photos
              and deliver notification emails.
            </li>
            <li>Law enforcement or regulators, only if we're legally required to.</li>
          </ul>
        </Section>

        <Section title="4. How long we keep it">
          <p>
            We keep account, booking, and walk records for as long as your account is active, and
            for a reasonable period after in line with tax and accounting requirements (GST
            invoices in particular must be retained for statutory record-keeping periods). When
            you ask us to delete your data, we deactivate the account and remove it from active
            use rather than keeping it visible anywhere in the app.
          </p>
        </Section>

        <Section title="5. Your choices">
          <ul className="ml-5 list-disc space-y-1.5">
            <li>You can update your profile, dogs, and addresses at any time from your account.</li>
            <li>You can ask us to export or delete your data by writing to us — see contact details below.</li>
            <li>You can opt out of email notifications by not adding an email to your profile; in-app notifications and OTP login messages are required for the service to function.</li>
          </ul>
        </Section>

        <Section title="6. Cookies">
          <p>
            We use a single essential cookie to keep you signed in (a session token). We don't use
            third-party advertising or tracking cookies.
          </p>
        </Section>

        <Section title="7. Security">
          <p>
            We restrict access to personal data to what's needed to run the service, and we never
            hard-delete records outright — accounts and bookings are deactivated rather than
            erased, so history stays auditable. No online service can guarantee perfect security,
            but we take reasonable, industry-standard measures to protect your information.
          </p>
        </Section>

        <Section title="8. Changes to this policy">
          <p>
            If we make material changes to this policy, we'll update the date at the top of this
            page. Continued use of Strollo after a change means you accept the updated policy.
          </p>
        </Section>

        <Section title="9. Contact us">
          <p>
            Questions about this policy or your data? Reach us at{" "}
            <a href={`mailto:${CONTACT.email}`} className="font-medium text-navy-600 underline underline-offset-2">
              {CONTACT.email}
            </a>{" "}
            or write to us at {addressOneLine()}.
          </p>
        </Section>
      </section>

      <SiteFooter />
    </main>
  );
}
